elevation_map_processing_node:
  ros__parameters:
    source_map_topic_name: "/elevation_mapping_node/elevation_map_filter" # Where to get raw elevation map from
    source_map_layer_name: "min_filter" # Check what layers are being published by elevation mapping node

    processed_map_topic_name: "/processed_elevation_map" # Where to publish
    # This is independent of how often an elevation map is received, as the transformation to base will occur more frequently using the latest tf. If you set this to zero bad things will happen :)
    # Set to a higher frequency than the policy inference because they are not synchronized, so it could happen that the inference timer runs 1ms too early and uses the previous (19ms old) data.
    # The more this frequency here is increased, the lower this delta can become
    processing_frequency_hz: 200.0

    # IMPORTANT: Dimensions of the map (i.e. (processed_map_grid_width * processed_grid_resolution, processed_map_grid_height * processed_grid_resolution)) is at most *half* the size of the map dimensions
    # configured in the elevation_mapping_cupy package publishing the raw map, so that out of bounds indices do not cause issues
    processed_map_grid_width: 13 # cells
    processed_map_grid_height: 11 # cells
    processed_map_grid_resolution: 0.08 # Meters
    elevation_sensor_offset_x: 0.2 # Meters, shifts sensor position relative to base, because policy was trained with a gridmap that is offset towards the front of the robot
    elevation_sensor_offset_y: 0.0 # Meters, shifts sensor position relative to base
    invalid_cell_fill_value: -0.27 # Meters, ONLY USED IF use_negative_base_height_as_fill_value is false
    use_negative_base_height_as_fill_value: true # If true, invalid_cell_fill_value is NOT used, and invalid cells are instead set to -base_height, which is arguably more accurate

    robot_base_frame_name: "vicon/Go2_Loukas/Go2_Loukas" # Base link of the robot
    max_tf_age: 0.01 # Max age of tf lookup before discarding iteration. Prevents using outdated pose of robot
    tf_lookup_timeout: 0.01 # Seconds to wait before aborting tf lookup

    min_allowed_base_height: 0.0 # In meters. Used to safely shut down robot when state estimation / odom reports unreasonable values.
    max_allowed_base_height: 1.0 # In meters. Used to safely shut down robot when state estimation / odom reports unreasonable values.