cat_control_node:
  ros__parameters:
    checkpoint_path: "/app/sim2real/traced_checkpoints/2025-06-28-17-13-04_21349_traced_deterministic.pt" # env 75, best one so far (with elevation map)
    # checkpoint_path: "/app/sim2real/traced_checkpoints/2025-06-28-17-13-04_6049_traced_deterministic.pt" # env 75, same as above just ealier checkpoint to show before vs. after energy minimization 
    use_hardcoded_elevation: false