services:
  cat_sim2real:
    pull_policy: build
    build:
      context: .
      args:
        progress: plain
      network: host
    image: cat-sim2real:latest
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TERM=xterm-256color
    # All this is needed for Tracy profiling
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - type: bind
        source: /sys/kernel/debug
        target: /sys/kernel/debug
        read_only: true
      # For tracy capture compilation inside container
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        bind:
          create_host_path: true
