services:
  cat_sim2real:
    pull_policy: build
    build:
      context: .
      network: host
    image: cat-sim2real:latest
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
      - TERM=xterm-256color
    # All this is needed for Tracy profiling
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - type: bind
        source: /sys/kernel/debug
        target: /sys/kernel/debug
        read_only: true
      # For tracy capture compilation inside container
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket